version: "3"

networks:
  tech-cat:

services:
  firebase:
    container_name: firebase-emulator
    build:
      context: ./
      dockerfile: Dockerfile
    image: techcat-firebase-development
    volumes:
      - ./:/volcano
    ports:
      - 7711:7711
      - 9099:9099
      - 9089:9089
      - 9079:9079
      - 4400:4400
      - 4500:4500